FRONTENDBOOTCAMP-13th/Friday13th

.prettierrc.cjs
index.html
package-lock.json
package.json

프리티어 설정
매번 작업 시 
git pull 
git branch 생성 후 push 가 기본
resolves #

프리티어 설정 및 하이패스 방지

---

src/style.css

- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 배포 테스트
- [] 최종 배포
resolves #

style.css 수정

---

src/components/main_header/main_header.css
src/components/main_header/main_header.html
src/components/main_nav/main_nav.css
src/components/main_nav/main_nav.html
src/js/animation.js
src/main.js

- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 배포 테스트
- [] 최종 배포
resolves #

nav components, main headera 수정

---

index.html
src/components/main_footer/main_footer_area1.css
src/components/main_footer/main_footer_area1.html
src/style.css

main_footer 작업중

---

index.html
src/components/smartphone/smartphone_button.css
src/components/smartphone/smartphone_text.css
src/components/smartphone/smartpone_cardcomponent.css
src/page/smartphone/smartphone_page.css
src/page/smartphone/smartphone_page.html
src/style.css

smartphone page / 0318 커밋

---

index.html
src/components/main_footer/main_footer.html
src/components/main_footer/main_footer_area2.css

area2.css 수정 및 하나로 합치는작업 완료
resolves #

area2.css 수정 및 하나로 합치기 완료

---

index.html
public/assets/icon/angle bracket.svg
src/components/frame/frame_location.css
src/components/frame/frame_location.html
src/components/frame/frame_shopping_cart.css
src/components/frame/frame_shopping_cart.html
src/style.css

Frame component location, shopping_cart 완성
resolves #

Frame component

---

src/components/main/header/main_header/main_header.css
src/components/main/header/main_nav/main_nav.css
src/components/main/header/main_search_bar/main_search_bar.css
src/components/search/search_menu.css
src/components/search/search_product.css
src/components/search/search_product.html
src/components/search/searchbar.css
src/components/smartphone/smartphone_nav.css
src/components/smartphone/smartphone_order.css
src/components/smartphone/smartphone_select_color.css
src/components/smartphone/smartphone_text.css
src/components/smartphone/smartpone_cardcomponent.css
src/page/search_page/search_page.css
src/page/search_page/search_page.html
src/page/smartphone/smartphone_page.css
src/style.css

main import css 경로 수정
resolves #

search page 구현 완

---

src/components/mypage/mypage_user_profile.html

mypage 컴포넌트 수정

---

src/components/mypage/mypage_class_registration.css
src/components/mypage/mypage_class_registration.html
src/components/mypage/mypage_favorite_products.css
src/components/mypage/mypage_favorite_products.html
src/components/mypage/mypage_order_status.css
src/components/mypage/mypage_order_status.html
src/components/mypage/mypage_product_management.css
src/components/mypage/mypage_product_management.html
src/components/mypage/mypage_qr_scanned_products.css
src/components/mypage/mypage_qr_scanned_products.html
src/components/mypage/mypage_recent_store.css
src/components/mypage/mypage_recent_store.html
src/components/mypage/mypage_review_write.css
src/components/mypage/mypage_review_write.html
src/components/mypage/mypage_smart_estimate.css
src/components/mypage/mypage_smart_estimate.html
src/components/mypage/mypage_user_profile.css
src/components/mypage/mypage_user_profile.html
src/page/mypage_page/mypage.html
src/style.css

- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 배포 테스트
- [] 최종 배포
resolves #

컴포넌트 완료 페이지 작업

---

src/components/mypage/mypage_class_registration.css
src/components/mypage/mypage_favorite_products.css
src/components/mypage/mypage_order_status.css
src/components/mypage/mypage_product_management.css
src/components/mypage/mypage_qr_scanned_products.css
src/components/mypage/mypage_recent_store.css
src/components/mypage/mypage_review_write.css
src/components/mypage/mypage_smart_estimate.css
src/components/mypage/mypage_user_profile.css
src/page/search_page/search_page.css

Login components correction

---

src/components/login/login_button.css
src/components/login/login_google.css
src/components/login/login_qr.css
src/components/login/login_qr.html

login margin값 추가

---

src/components/mypage/mypage_class_registration.css
src/components/mypage/mypage_favorite_products.css
src/components/mypage/mypage_order_status.css
src/components/mypage/mypage_product_management.css
src/components/mypage/mypage_qr_scanned_products.css
src/components/mypage/mypage_recent_store.css
src/components/mypage/mypage_review_write.css
src/components/mypage/mypage_smart_estimate.css
src/components/mypage/mypage_user_profile.css
src/page/mypage_page/mypage.css
src/page/mypage_page/mypage.html

- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- [] 배포 테스트
- [] 최종 배포
resolves #

mypage page 완성

---

public/assets/icon/header_files/icon-slick-next-compo-wht.svg.svg
public/assets/icon/header_files/icon-slick-prev-compo-wht.svg.svg
src/components/main/main_compo/main_banner.css
src/components/main/main_compo/main_banner.html
src/js/banner.js
src/main.js

main_banner 완성

---

src/components/main_footer/main_footer_final.css

footer 찐 완성

---

src/components/main_footer/main_footer_final.html

Main card component

---

index.html
src/components/cardcomponent/card_component_button.css
src/components/cardcomponent/card_component_button.html
src/components/login/login_account.css
src/components/login/login_button.css
src/components/login/login_button.html
src/components/login/login_checkbox.css
src/components/login/login_email.css
src/components/login/login_google.css
src/components/login/login_google.html
src/components/login/login_header.css
src/components/login/login_header.html
src/components/login/login_id.css
src/components/login/login_ment1.css
src/components/login/login_ment1.html
src/components/login/login_ment2.css
src/components/login/loginpage.css
src/components/login/loginpage.html
src/page/login_page/loginpage.css
src/page/login_page/loginpage.html
src/style.css

login page 구현

---

src/page/smartphone/smartphone_page.html
src/page/tv_page/tv_page.html

- smartphone page footer 추가 및 title 변경

---

src/page/tv_page/tv_page.html

- tv page footer 추가 및 title 변경

---

src/components/main/main_compo/main_cardpro.css
src/components/main/main_compo/main_cardpro.html
vite.config.js

Main card components

---

src/components/search/search_menu.css
src/components/search/search_product.css
src/components/search/search_product.html
src/components/search/searchbar.css
src/components/search/searchbar.html
src/page/login_page/loginpage.css
src/page/search_page/search_page.css
src/page/search_page/search_page.html

- search page 디자인 재수정

---

index.html
public/assets/icon/pay/arrow.up.svg
public/assets/icon/pay/arrow_down.svg
public/assets/icon/pay/arrow_right.svg
src/components/pay/pay_button.css
src/components/pay/pay_button.html
src/style.css

pay_button 완성

---

src/components/pay/pay_address.css
src/components/pay/pay_address.html
src/components/pay/pay_address_find.css
src/components/pay/pay_address_find.html
src/components/pay/pay_delivery.css
src/components/pay/pay_delivery.html
src/components/pay/pay_orderer.css
src/components/pay/pay_orderer.html
src/page/mypage_page/mypage.css
src/page/mypage_page/mypage.html

- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 배포 테스트
- [] 최종 배포
resolves #

Pay components

---

index.html
src/page/frame_page/frame_page.html
vite.config.js

index, vite 현재까지 작업 정리 완료
resolves #

index 정리, vite.config 정리

---

src/page/mypage_page/mypage.css
src/page/mypage_page/mypage.html

- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 배포 테스트
- [] 최종 배포
resolves #

mypage css 수정

---

README.md

- reademe 뱃지 및 내용 추가

---

src/components/mypage/mypage_class_registration.css
src/components/mypage/mypage_user_profile.css
src/style.css

- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 배포 테스트
- [] 최종 배포
resolves #

mypage_page css 수정
